<?php
declare(strict_types=1);

// NpmRegistry SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

NpmRegistryUtility::setRegistrar(function (NpmRegistryUtility $u): void {
    $u->clean = [NpmRegistryClean::class, 'call'];
    $u->done = [NpmRegistryDone::class, 'call'];
    $u->make_error = [NpmRegistryMakeError::class, 'call'];
    $u->feature_add = [NpmRegistryFeatureAdd::class, 'call'];
    $u->feature_hook = [NpmRegistryFeatureHook::class, 'call'];
    $u->feature_init = [NpmRegistryFeatureInit::class, 'call'];
    $u->fetcher = [NpmRegistryFetcher::class, 'call'];
    $u->make_fetch_def = [NpmRegistryMakeFetchDef::class, 'call'];
    $u->make_context = [NpmRegistryMakeContext::class, 'call'];
    $u->make_options = [NpmRegistryMakeOptions::class, 'call'];
    $u->make_request = [NpmRegistryMakeRequest::class, 'call'];
    $u->make_response = [NpmRegistryMakeResponse::class, 'call'];
    $u->make_result = [NpmRegistryMakeResult::class, 'call'];
    $u->make_point = [NpmRegistryMakePoint::class, 'call'];
    $u->make_spec = [NpmRegistryMakeSpec::class, 'call'];
    $u->make_url = [NpmRegistryMakeUrl::class, 'call'];
    $u->param = [NpmRegistryParam::class, 'call'];
    $u->prepare_auth = [NpmRegistryPrepareAuth::class, 'call'];
    $u->prepare_body = [NpmRegistryPrepareBody::class, 'call'];
    $u->prepare_headers = [NpmRegistryPrepareHeaders::class, 'call'];
    $u->prepare_method = [NpmRegistryPrepareMethod::class, 'call'];
    $u->prepare_params = [NpmRegistryPrepareParams::class, 'call'];
    $u->prepare_path = [NpmRegistryPreparePath::class, 'call'];
    $u->prepare_query = [NpmRegistryPrepareQuery::class, 'call'];
    $u->graphql_body = [NpmRegistryGraphql::class, 'body'];
    $u->graphql_errors = [NpmRegistryGraphql::class, 'errors'];
    $u->result_basic = [NpmRegistryResultBasic::class, 'call'];
    $u->result_body = [NpmRegistryResultBody::class, 'call'];
    $u->result_headers = [NpmRegistryResultHeaders::class, 'call'];
    $u->transform_request = [NpmRegistryTransformRequest::class, 'call'];
    $u->transform_response = [NpmRegistryTransformResponse::class, 'call'];
});
